Patch 20
dockserver/dockserver pull request #170
Opened 2021-08-07 13:38 UTC by brtbach

2021-08-07 13:39 UTC, brtbach commented
switch to linuxserver image (pgid&puid jail)
changed valume according to linuxsever docker image
fixed version to 10.5.11-r0 (newer versions cause issues with nextcloud)
disabled auto update

2021-08-07 13:57 UTC, doob187 requested changes
See Infos

2021-08-07 13:57 UTC, doob187 commented on apps/addons/mariadb.yml
> +      - 'MYSQL_ROOT_PASSWORD=password'
Change  this to environment back

2021-08-07 13:57 UTC, doob187 commented on apps/addons/mariadb.yml
> +    image: 'linuxserver/mariadb:amd64-alpine-version-10.5.11-r0'
Add this environment.
Not all runs amd versions 
Some runs it on arm

2021-08-08 17:13 UTC, DrAg0n141 commented
@doob187 it is all fixed :)

2021-08-08 17:15 UTC, doob187 reviewed
#patch

2021-08-08 17:15 UTC, merged