Add `krusader` to addons.
dockserver/dockserver pull request #210
Opened 2021-09-06 22:11 UTC by aelfa

2021-09-07 10:34 UTC, doob187 requested changes
Add environments also to 

https://github.com/dockserver/dockserver/blob/master/traefik/templates/compose/.env

2021-09-07 19:25 UTC, aelfa commented
@doob187 On it now!

2021-09-07 19:29 UTC, aelfa commented
@doob187 Done! Kindly review.

2021-09-08 06:46 UTC, doob187 requested changes
Read notes

2021-09-08 06:46 UTC, doob187 commented on apps/addons/krusader.yml
> +      - 'WEBPAGE_TITLE=Tower'
Environment pls

2021-09-10 16:23 UTC, doob187 reviewed
One changes plz then 

👍

2021-09-10 16:23 UTC, doob187 commented on apps/addons/plex-update-tool.yml
> +      - 'RUN_EVERY_N_HOURS=12'
Variable  plz

Made customizable possible

2021-09-11 01:01 UTC, doob187 approved these changes

2021-09-11 01:03 UTC, merged