KASM Containers
dockserver/dockserver pull request #244
Opened 2021-10-09 19:05 UTC by justinglock40

2021-10-09 20:08 UTC, doob187 requested changes
Fix PLZ

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/chrome.yml
> +      - 'VNC_PW=password'
No Hardcoded Value

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/discord.yml
> +      - 'VNC_PW=password'
Same.here

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/discord.yml
> +      - '6905:6901'
BLOCKPORT missed

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/chrome.yml
> +      - '6902:6901'
BLOCKPORT missed

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/discord.yml
> +      - '/mnt:/mnt'
Use unionfs Local persistent mode

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/firefox.yml
> +      - '6906:6901'
BLOCKPORT again

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/firefox.yml
> +      - '/mnt:/mnt'
Same here use Local persistent

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/onlyoffice.yml
> +      - 'VNC_PW=password'
Password need value in env

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/onlyoffice.yml
> +      - '6909:6901'
BLOCKPORT  again

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/signal.yml
> +      - 'VNC_PW=password'
Value again

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/signal.yml
> +      - '6904:6901'
BLOCKPORT again

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/steam.yml
> +    networks:
Env again

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/steam.yml
> +      - '6903:6901'
BLOCKPORT

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/telegram.yml
> +      - 'VNC_PW=password'
Emv

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/telegram.yml
> +      - '/mnt:/mnt'
Local persistent

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/telegram.yml
> +      - '6905:6901'
BLOCKPORT

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/tor.yml
> +      - 'VNC_PW=password'
Env

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/tor.yml
> +      - '6908:6901'
BLOCKPORT

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/tor.yml
> +      - '/mnt:/mnt'
Local persistent

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/vlc.yml
> +      - 'VNC_PW=password'
Env

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/vlc.yml
> +      - '6907:6901'
BLOCKPORT

2021-10-09 20:08 UTC, doob187 commented on apps/kasmworkspace/vlc.yml
> +      - '/mnt:/mnt'
Local persistent

2021-10-09 21:08 UTC, doob187 approved these changes
👍 from.my side

@drag0n141

2021-10-10 09:43 UTC, drag0n141 approved these changes
Looks good :)

2021-10-10 14:02 UTC, merged